--- 
title: "Análise Descritiva e Comparativa da Covid-19"
author: "Guilherme Fernandes Castro de Oliveira"
date: "`r paste('Última atualização:', format(Sys.Date(), '%d/%m/%Y'))`"
site: bookdown::bookdown_site
documentclass: ic
classoption: fleqn,ebook
bibliography: [ic.bib, packages.bib]
biblio-style: abbrvnat3
nocite: "@*"
link-citations: yes
favicon: "img/favicon.ico"
description: "Iniciação Científica aprovado no edital PIBIC 2020"
---

\begin{acknowledgement}

  Aqui você deve colocar os agradecimentos. Por exemplo:
  
  Primeiramente queria agradecer ao meu orientador Fernando de Souza Bastos por
  sempre estar me ajudando em qual seja o assunto ou dificuldade, a aprender
  cada vez mais sobre o R e sua comunidade, e pela consideração que tem comigo e
  todos os seus alunos.
  
  Agradeço aos meus amigos que sempre me deixam pra cima nos momentos mais
  difíceis e que nunca abandonam quando preciso deles.

  Agradeço também a Júlia Letícia Gonçalves Martins na ajuda na escrita desse
  exemplo de TCC, e todo o apoio nos projetos da minha vida.
  
  Agradeço a todos que fizeram parte da minha vida e me ensinaram algo, sendo
  assim ajudaram nesse trabalho indiretamente.
  
  E agradeço a você que utilizará esse modelo pela consideração.

\end{acknowledgement}
\begin{Resumo}
  
  Aqui você deve colocar o seu resumo. Por exemplo:
  
  Até os dias atuais, o curso de Licenciatura em Matemática da UFV - Campus 
  Florestal possui um protótipo para escrita do Trabalho de Conclusão do Curso
  criado na linguagem LaTeX, elaborado pelo professor Luis Alberto D'Afonseca, 
  disponível no site da graduação. Embasado nesse modelo já existente, este novo
  modelo foi criado com o pacote Bookdown para que pudesse ser escrito não 
  somente em LaTeX, mas também nas linguagens citadas acima, com o diferencial 
  mais importante o R e seus pacotes.
  
  É válido ressaltar que este padrão pode ser utilizado não somente pelo curso
  de Licenciatura em Matemática - Campus Florestal, mas sim por todos os cursos
  dos campus da Universidade Federal de Viçosa.
  
  Espero que todos utilizem, consigam fazer o seu TCC e enfim recebam o tão
  desejado diploma.
  
\end{Resumo}
\begin{Abstract}
  
  Aqui você deve colocar o seu rusumo em inglês. Por exemplo:
  
  Until today, the Mathematics Degree course at UFV - Campus Florestal has a
  prototype for writing the Course Conclusion Paper created in LaTeX language,
  elaborated by professor Luis Alberto D'Afonseca, available on the graduation
  website. Based on this existing model, this new model was created with the
  Bookdown package so that it could be written only in LaTeX, but also in the
  languages mentioned above, with the differential most importantly R and its
  packages.
  
  It is worth noting that this standard can be used not only by the course in
  Mathematics - Campus Florestal, but for all courses campus of the Federal
  University of Viçosa.
  
  I hope you all use it, get your TCC and finally receive the so desired
  University Degree.
  
\end{Abstract}

\tableofcontents